import WordCloud from "wordcloud";

// const mockedData = [
//   ["Staking", 64],
//   ["(3,3)", 11],
//   ["AMM", 16],
//   ["Impermanent loss", 17],
//   ["Seed Phrase", 10],
//   ["Liquidity Pool", 54],
//   ["WAGMI", 12],
//   ["Vesting", 77],
//   ["Yield Farming", 45],
//   ["left", 19],
//   ["pay", 13],
//   ["people", 32],
//   ["month", 22],
//   ["again", 35],
//   ["review", 24],
//   ["call", 38]
// ];

const mockedData = [
  ["Staking", 72],
  ["(3,3)", 54],
  ["AMM", 53],
  ["Impermanent loss", 51],
  ["Seed Phrase", 44],
  ["Liquidity Pool", 38],
  ["WAGMI", 35],
  ["Vesting", 34],
  ["Yield Farming", 34],
  ["Staking", 30],
  ["(3,3)", 28],
  ["AMM", 27],
  ["Impermanent loss", 27],
  ["Seed Phrase", 26],
  ["Liquidity Pool", 25],
  ["WAGMI", 25],
  ["Vesting", 25],
  ["Yield Farming", 24],
  ["Staking", 24],
  ["(3,3)", 21],
  ["AMM", 21],
  ["Impermanent loss", 21],
  ["Seed Phrase", 19],
  ["Liquidity Pool", 19],
  ["WAGMI", 18],
  ["Vesting", 18],
  ["Yield Farming", 17]
  // ["大仙", 17],
  // ["明星", 17],
  // ["老师", 16],
  // ["曝光", 15],
  // ["现场", 14],
  // ["一哥", 14],
  // ["韦神", 14],
  // ["联盟", 13],
  // ["女主播", 13],
  // ["季度", 13],
  // ["发展", 13],
  // ["选手", 12],
  // ["全球", 12],
  // ["回应", 12],
  // ["女孩", 12],
  // ["投票", 12],
  // ["财报", 11],
  // ["短视", 11],
  // ["世界", 11],
  // ["中国", 11],
  // ["颜值", 11],
  // ["开启", 10],
  // ["背后", 10],
  // ["打野", 10],
  // ["阵容", 9],
  // ["透露", 9],
  // ["正式", 9],
  // ["双十一", 9],
  // ["总决赛", 8],
  // ["轻松", 8],
  // ["时代", 7],
  // ["状态", 7],
  // ["增长", 7],
  // ["年度", 7]
];

WordCloud(document.getElementById("problem-text"), {
  list: mockedData,
  gridSize: 4,
  color: function (word, weight) {
    return (weight === 12) ? '#f02222' : '#c09292';
  },
  backgroundColor: 'transparent',
  weightFactor: 0.5,
  rotateRatio: 0,
  rotationSteps: 2,
  shape: "circle",
  ellipticity: 0.3,
  fontFamily: "Poppins, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif"
});
